version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: bi-db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "15432:5432"
    volumes:
      - bi_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: bi-back
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - "8443:8443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  bi_data:
    name: bi_data
