spring.applicatsion.name=bi-back

server.port=8080
server.forward-headers-strategy=framework
server.servlet.context-path=/bi
server.servlet.session.cookie.name=BI_SESSION_ID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true
spring.session.store-type=jdbc

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:15432/test
spring.datasource.username=test
spring.datasource.password=test

spring.liquibase.change-log=db/migration/changelog-master.xml
spring.liquibase.enabled=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.jpa.open-in-view=false
app.frontend.origin=http://localhost:3000

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

management.endpoints.web.exposure.include=health,info